Data model
looh16/blog_app pull request #1
Opened 2022-11-01 20:00 UTC by looh16

**Build your project schema :**

> Create necessary migration files.
> Add Foreign keys.
> Add a corresponding index. to all foreign keys

2022-11-01 20:29 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Langa, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-01 20:29 UTC, SajjadAhmad14 commented on db/migrate/20221101192600_create_posts.rb
> +      t.references :user, null: false, foreign_key: true
Please add `author_id` as a foreign key instead of `user_id` as it's specified in the requirements.

2022-11-01 20:29 UTC, SajjadAhmad14 commented on db/migrate/20221101193016_create_comments.rb
> +      t.references :user, null: false, foreign_key: true
Please add `author_id` as a foreign key instead of `user_id` as it's specified in the requirements.

2022-11-01 20:29 UTC, SajjadAhmad14 commented on db/migrate/20221101194105_create_likes.rb
> +      t.references :user, null: false, foreign_key: true
Please add `author_id` as a foreign key instead of `user_id` as it's specified in the requirements.

2022-11-01 22:26 UTC, mateo951 approved these changes
### Hi @looh16, 

Well done making the required changes by the previous reviewer 🔥
Your project is complete!  There is nothing else to say other than... it's time to merge it 🐐 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 07:15 UTC, looh16 commented
Thanks!

2022-11-02 07:15 UTC, merged